const defaultTheme = require("tailwindcss/defaultTheme");

export const fonts = {
  sans: ["-apple-system", ...defaultTheme.fontFamily.sans],
  poppins: ["poppins"],
  vina: ["Vina Sans", "sans-serif"],
  dancing: ["Dancing Script", "cursive"],
  lobster: ["Lobster", "sans-serif"],
  ballet: ["Ballet", "cursive"],
  bebas: ["Bebas Neue", "sans-serif"],
  caveat: ["Caveat", "cursive"],
  Englebert: ["Englebert", "cursive"],
  Exo: ["Exo 2", "sans-serif"],
  Gluten: ["Gluten", "cursive"],
  Grandiflora: ["Grandiflora One", "cursive"],
  GreatVibes: ["Great Vibes", "cursive"],
  Inconsolata: ["Inconsolata", "monospace"],
  openSans: ["Open Sans", " sans-serif"],
  pacifico: ["Pacifico", "cursive"],
  Playfair: ["Playfair Display", "serif"],
  Sacramento: ["Sacramento", "cursive"],
  Satisfy: ["Satisfy", "cursive"],
  Shadows: ["Shadows Into Light", "cursive"],
  Courier: ["Courier New"],
  Consolas: ["Consolas"],
  Alex: ["Alex Brush", "cursive"],
  Allura: ["Allura", "cursive"],
  Anton: ["Anton", "sans-serif"],
  Arizonia: ["Arizonia", "cursive"],
  Bad: ["Bad Script", "cursive"],
  Bilbo: ["Bilbo Swash Caps", "cursive"],
  Charm: ["Charm", "cursive"],
  Cookie: ["Cookie", "cursive"],
  Courgette: ["Courgette", "cursive"],
  Dhurjati: ["Dhurjati", "sans-serif"],
  Ephesis: ["Ephesis", "cursive"],
  Handlee: ["Handlee", "cursive"],
  Homemade: ["Homemade Apple", "cursive"],
  Indie: ["Indie Flower", "cursive"],
  Kaushan: ["Kaushan Script", "cursive"],
  Leckerli: ["Leckerli One", "cursive"],
  Mali: ["Mali", "cursive"],
  Marck: ["Marck Script", "cursive"],
  Dafoe: ["Mr Dafoe", "cursive"],
  saint: ["Mrs Saint Delafield", "cursive"],
  Nechua: ["Neucha", "cursive"],
  Norican: ["Norican", "cursive"],
  Nova: ["Nova Square", "sans-serif"],
  Baby: ["Oooh Baby", "cursive"],
  Orbitron: ["Orbitron", "sans-serif"],
  Parisienne: ["Parisienne", "cursive"],
  Passion: ["Passion One", "sans-serif"],
  Patrick: ["Patrick Hand", "cursive"],
  Pinyon: ["Pinyon Script", "cursive"],
  Pixelify: ["Pixelify Sans", "sans-serif"],
  Playball: ["Playball", "cursive"],
  Prata: ["Prata", "serif"],
  Qwigley: ["Qwigley", "cursive"],
  Reenie: ["Reenie Beanie", "cursive"],
  Rock: ["Rock Salt", "cursive"],
  Rowdies: ["Rowdies", "sans-serif"],
  Saira: ["Saira Extra Condensed", "sans-serif"],
  Srabun: ["Sarabun", "sans-serif"],
  Shalimar: ["Shalimar", "cursive"],
  Smooch: ["Smooch", "cursive"],
  Smooch_Sans: ["Smooch Sans", "sans-serif"],
  Tangerine: ["Tangerine", "cursive"],
  Nautigal: ["The Nautigal", "cursive"],
  Yellowtail: ["Yellowtail", "cursive"],
  Yesteryear: ["Yesteryear", "cursive"],
  Zeyada: ["Zeyada", "cursive"],
};
